version: '3.8'

services:
  api1:
    build:
      dockerfile: Dockerfile
      context: .
    image: api
    network_mode: host
    hostname: api1
    restart: "on-failure"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '9090'
    links:
      - db
    environment:
      API_PORT: 9090
      POSTGRES_HOST: localhost
      POSTGRES_DB: db_cake
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_PORT: 5432
    command: npm run start
    deploy:
      resources:
        limits:
          cpus: '0.175'
          memory: '125MB'

  api2:
    build:
      dockerfile: Dockerfile
      context: .
    image: api
    network_mode: host
    hostname: api2
    restart: "on-failure"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '9091'
    links:
      - db
    environment:
      API_PORT: 9091
      POSTGRES_HOST: localhost
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
      POSTGRES_PORT: 5432
    command: npm run start
    deploy:
      resources:
        limits:
          cpus: '0.175'
          memory: '125MB'

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '30MB'

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    network_mode: host
    hostname: db
    restart: "on-failure"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '270MB'

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"