version: '3.5'

services:
  api1:
    image: redvelvetdev/app:latest
    hostname: api1
    restart: always
    depends_on:
      - db
      - redis
    expose:
      - '80'
    links:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2:
    image: redvelvetdev/app:latest
    hostname: api2
    restart: always
    depends_on:
      - db
      - redis
    expose:
      - '80'
    links:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.3GB'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.3GB'

  db:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    command: postgres -c 'max_connections=5000'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '1.4GB'
