version: '3.5'

services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    restart: "on-failure"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    command: postgres -c 'max_connections=6000'
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '1.5GB'