version: '3.8'

services:
  api1:
    build:
      dockerfile: Dockerfile
      context: .
    image: api
    network_mode: host
    hostname: api1
    restart: "on-failure"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '9090'
    links:
      - db
    environment:
      API_PORT: 9090
      POSTGRES_HOST: localhost
      POSTGRES_DB: db_cake
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_PORT: 5432
    command: npm run start
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '80MB'

  api2:
    build:
      dockerfile: Dockerfile
      context: .
    image: api
    network_mode: host
    hostname: api2
    restart: "on-failure"
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '9091'
    links:
      - db
    environment:
      API_PORT: 9091
      POSTGRES_HOST: localhost
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
      POSTGRES_PORT: 5432
    command: npm run start
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '80MB'

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.95'
          memory: '130MB'

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    network_mode: host
    hostname: db
    restart: "on-failure"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: cake
      POSTGRES_PASSWORD: cake123
      POSTGRES_DB: db_cake
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    command: postgres -c 'max_connections=6000'
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '260MB'
